apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myservice
  namespace: default
  annotations:
    # Tell nginx to talk HTTPS to the backend
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Enable SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # mTLS configuration for upstream
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "default/myservice-client-cert"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "2"
    nginx.ingress.kubernetes.io/proxy-ssl-trusted-ca: "default/myservice-ca"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "myservice.example.com"

spec:
  tls:
    - hosts:
        - myservice.example.com
      secretName: myservice-cert
  ingressClassName: nginx
  rules:
    - host: myservice.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myservice
                port:
                  number: 8443